-- ============================================================
--  WC2026 Prediction Game — Supabase Database Schema
--  Run this entire file in your Supabase SQL Editor
-- ============================================================

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";


-- ============================================================
--  TABLE: profiles
--  Extends auth.users with display name, avatar, admin flag
-- ============================================================
CREATE TABLE IF NOT EXISTS public.profiles (
  id              UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  display_name    TEXT,
  avatar_color    TEXT DEFAULT '#f0b429',
  is_admin        BOOLEAN DEFAULT FALSE,
  invite_code_used TEXT,
  email           TEXT,                    -- denormalised for admin panel display
  created_at      TIMESTAMPTZ DEFAULT NOW(),
  updated_at      TIMESTAMPTZ DEFAULT NOW()
);

-- Auto-create profile on auth.user signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER LANGUAGE PLPGSQL SECURITY DEFINER SET search_path = public AS $$
BEGIN
  INSERT INTO public.profiles (id, display_name, email)
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data->>'display_name', split_part(NEW.email, '@', 1)),
    NEW.email
  )
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();


-- ============================================================
--  TABLE: invite_codes
--  Invite codes generated by admin; validated at signup
-- ============================================================
CREATE TABLE IF NOT EXISTS public.invite_codes (
  id          UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  code        TEXT UNIQUE NOT NULL,                -- 6-char uppercase code
  label       TEXT,                               -- friendly label (e.g. "For John")
  active      BOOLEAN DEFAULT TRUE,
  created_at  TIMESTAMPTZ DEFAULT NOW()
);

-- Seed one invite code for initial setup
-- Remove or replace this after first use
INSERT INTO public.invite_codes (code, label, active)
VALUES ('KICKOFF', 'Initial setup code', TRUE)
ON CONFLICT DO NOTHING;


-- ============================================================
--  TABLE: predictions
--  One row per user × round × question
-- ============================================================
CREATE TABLE IF NOT EXISTS public.predictions (
  id           UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  user_id      UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  round        TEXT NOT NULL,               -- 'round1'…'round8'
  question_key TEXT NOT NULL,              -- e.g. '1.1', '2.w.A', 'm1'
  value        TEXT NOT NULL,              -- JSON-encoded value
  updated_at   TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (user_id, round, question_key)
);

CREATE INDEX IF NOT EXISTS idx_predictions_user ON public.predictions(user_id);
CREATE INDEX IF NOT EXISTS idx_predictions_round ON public.predictions(round);
CREATE INDEX IF NOT EXISTS idx_predictions_match ON public.predictions(question_key)
  WHERE question_key LIKE 'm%';


-- ============================================================
--  TABLE: scores
--  One row per user — running round-by-round totals
-- ============================================================
CREATE TABLE IF NOT EXISTS public.scores (
  id               UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  user_id          UUID REFERENCES auth.users(id) ON DELETE CASCADE UNIQUE NOT NULL,
  round1_points    INTEGER DEFAULT 0,
  round2_points    INTEGER DEFAULT 0,
  round3_points    INTEGER DEFAULT 0,
  round4_points    INTEGER DEFAULT 0,
  round5_points    INTEGER DEFAULT 0,
  round6_points    INTEGER DEFAULT 0,
  round7_points    INTEGER DEFAULT 0,
  round8_points    INTEGER DEFAULT 0,
  total_points     INTEGER DEFAULT 0,
  updated_at       TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_scores_total ON public.scores(total_points DESC);


-- ============================================================
--  TABLE: match_results
--  Final/live scores per match; admin or API-synced
-- ============================================================
CREATE TABLE IF NOT EXISTS public.match_results (
  match_id    INTEGER PRIMARY KEY,           -- matches GROUP_FIXTURES id / KNOCKOUT id
  home_score  INTEGER,
  away_score  INTEGER,
  status      TEXT DEFAULT 'TIMED',          -- TIMED | IN_PLAY | PAUSED | FINISHED
  home_team   TEXT,                          -- for knockout matches
  away_team   TEXT,
  updated_at  TIMESTAMPTZ DEFAULT NOW()
);


-- ============================================================
--  ROW LEVEL SECURITY
-- ============================================================

ALTER TABLE public.profiles      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.invite_codes  ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.predictions   ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.scores        ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.match_results ENABLE ROW LEVEL SECURITY;


-- ---- profiles ----
-- Everyone can read profiles (for leaderboard display names/avatars)
CREATE POLICY "profiles: public read"
  ON public.profiles FOR SELECT USING (TRUE);

-- Users can update their own profile
CREATE POLICY "profiles: own update"
  ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- Users can insert their own profile (triggered by handle_new_user, but allow direct too)
CREATE POLICY "profiles: own insert"
  ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);


-- ---- invite_codes ----
-- Anyone can read invite codes to validate at signup
CREATE POLICY "invite_codes: public read"
  ON public.invite_codes FOR SELECT USING (TRUE);

-- Only admins can insert/update invite codes
CREATE POLICY "invite_codes: admin write"
  ON public.invite_codes FOR ALL USING (
    EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND is_admin = TRUE)
  );


-- ---- predictions ----
-- Users can read all predictions (for match centre - shows everyone's picks)
CREATE POLICY "predictions: public read"
  ON public.predictions FOR SELECT USING (TRUE);

-- Users can only write their own predictions
CREATE POLICY "predictions: own write"
  ON public.predictions FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "predictions: own update"
  ON public.predictions FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "predictions: own delete"
  ON public.predictions FOR DELETE USING (auth.uid() = user_id);


-- ---- scores ----
-- Everyone can read scores (for leaderboard)
CREATE POLICY "scores: public read"
  ON public.scores FOR SELECT USING (TRUE);

-- Only admins or service_role can write scores
-- (Scores are updated by the recalculate Edge Function using service_role key)
CREATE POLICY "scores: admin write"
  ON public.scores FOR ALL USING (
    EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND is_admin = TRUE)
  );


-- ---- match_results ----
-- Everyone can read match results
CREATE POLICY "match_results: public read"
  ON public.match_results FOR SELECT USING (TRUE);

-- Only admins can write match results
CREATE POLICY "match_results: admin write"
  ON public.match_results FOR ALL USING (
    EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND is_admin = TRUE)
  );


-- ============================================================
--  HELPER FUNCTION: Set first registered user as admin
--  Call this manually after your own account is created:
--  SELECT set_admin_by_email('your@email.com');
-- ============================================================
CREATE OR REPLACE FUNCTION public.set_admin_by_email(admin_email TEXT)
RETURNS VOID LANGUAGE PLPGSQL SECURITY DEFINER AS $$
DECLARE
  target_id UUID;
BEGIN
  SELECT id INTO target_id FROM auth.users WHERE email = admin_email LIMIT 1;
  IF target_id IS NOT NULL THEN
    UPDATE public.profiles SET is_admin = TRUE WHERE id = target_id;
    RAISE NOTICE 'Admin set for %', admin_email;
  ELSE
    RAISE EXCEPTION 'User not found: %', admin_email;
  END IF;
END;
$$;


-- ============================================================
--  REALTIME: Enable on tables that need live updates
-- ============================================================
-- Run these in Supabase Dashboard > Database > Replication
-- or via SQL:
ALTER PUBLICATION supabase_realtime ADD TABLE public.scores;
ALTER PUBLICATION supabase_realtime ADD TABLE public.match_results;
ALTER PUBLICATION supabase_realtime ADD TABLE public.predictions;


-- ============================================================
--  GRANT permissions to authenticated and anon roles
-- ============================================================
GRANT USAGE ON SCHEMA public TO anon, authenticated;
GRANT SELECT ON public.profiles TO anon, authenticated;
GRANT SELECT ON public.invite_codes TO anon, authenticated;
GRANT SELECT ON public.predictions TO anon, authenticated;
GRANT SELECT ON public.scores TO anon, authenticated;
GRANT SELECT ON public.match_results TO anon, authenticated;

GRANT INSERT, UPDATE ON public.profiles TO authenticated;
GRANT INSERT, UPDATE, DELETE ON public.predictions TO authenticated;

-- Admin writes via service_role (Edge Function) or authenticated admin
GRANT INSERT, UPDATE, DELETE ON public.scores TO authenticated;
GRANT INSERT, UPDATE, DELETE ON public.match_results TO authenticated;
GRANT INSERT, UPDATE, DELETE ON public.invite_codes TO authenticated;
